### ISSUE TITLE
Character issue in Google results

### ISSUE THREAD

**Issue by ardatdev** [Artado-Project/ArtadoProxy#2]
As you can see in the code below
```
const urlnospace = displayUrl.replace(/ /g, '');
let url = urlnospace.replace(/›/g, '');
```

This code first replaces the spaces in the displayUrl. Then should change the "›" character into "/".
But it doesn't work. I have searched and tried many things. 

Example on how it should work:

displayUrl = "onedio.com › test"
urlnospace = "onedio.com›test"
url = "onedio.com/test"

The problem is in the last step.

**Comment by yasinldev** [comment]
please see c79031a
